
name: Django CI version1

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
jobs:
  ci:
    name: Lint, Security, Migrations, Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      DJANGO_SETTINGS_MODULE: config.settings.dev
      DJANGO_SECRET_KEY: test-secret-key
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: 127.0.0.1,localhost,testserver
      DB_ENGINE: django.db.backends.sqlite3
      DB_NAME: db.sqlite3
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt


      - name: Show Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Check for dependency issues
        run: pip check

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Ruff
        run: ruff check .

      - name: Run Black
        run: black --check .

      #- name: Run Bandit and save report
      #  run: |
      #    bandit -r . -x tests -f json -o reports/bandit-report.json || true
      #    bandit -r . -x tests

      #- name: Run pip-audit and save report
      #  run: |
      #    pip-audit -f json -o reports/pip-audit-report.json || true
      #    pip-audit

      - name: Django system checks
        run: python manage.py check

      - name: Check for missing migrations
        run: python manage.py makemigrations --check --dry-run | tee reports/makemigrations-check.txt

      - name: Apply migrations
        run: python manage.py migrate --noinput | tee reports/migrate-output.txt

      - name: Run Django tests with coverage
        run: coverage run manage.py test -v 2 | tee reports/test-output.txt

      - name: Generate coverage XML report
        if: always()
        run: coverage xml -o reports/coverage.xml

      - name: Generate coverage HTML report
        if: always()
        run: coverage html -d reports/htmlcov

      - name: Show coverage report and enforce minimum threshold
        run: coverage report -m --fail-under=70 | tee reports/coverage-summary.txt

      - name: Upload reports artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-reports
          path: reports/
